### ISSUE TITLE
Стили для слайдшоу

### ISSUE THREAD

**Issue by edgiru** [rvalitov/widgetkit-slideshow-ex#2]
Добрый день!
Раньше в первой версии widgetkit наследовались стили от шаблона для слайдшоу, а теперь в настройках нет и стиль не наследуется с шаблона. Неужели придется все подправлять вручную?

**Comment by rvalitov** [comment]
Если речь идет о шаблоне дизайна (Warp 7), то виджет их наследует. 

Если речь идет о стилях (настройках), которые были в старом Widgetkit, то в новом их нет. Это относится не к данному виджету, а всему Widgetkit в целом. Widgetkit 1 и Widgetkit 2 - это совершенно разные продукты, между собой не совместимые, соответственно наследования функционала тоже нет.

Если же Вы имели ввиду что-то другое, то пожалуйста, поясните.
