### ISSUE TITLE
Not Compatible With IE9?

### ISSUE THREAD

**Issue by acaffeinateddev** [rvalitov/widgetkit-slideshow-ex#3]
Hello! I know IE9 is old and out of date, but I use your plugin for one of my jobs and it works beautifully in Chrome/Firefox/etc, but does not display at all in IE. The only styles I have that prevent display are responsive styles that kick in at much smaller resolutions. I can't link you publicly to the site, but if there's any further information I can provide, please let me know! Thank you!

**Comment by rvalitov** [comment]
Hi! My widget has the same requirements as the original widget of the Yootheme. Can you please do the following to check the reason of the problem:
- check if standard Slideshow widget works in IE on your website
- check the error log: both in the browser's console error output and in the error.log file of Apache and PHP (you may need to turn on maximum level of debug in the settings of Joomla first)
- test the website that is provided as an example (the link is at the bottom of this wiki page https://github.com/rvalitov/widgetkit-slideshow-ex/wiki/How-to-make-the-whole-slide-clickable ). Provide the screenshot of what you see in IE.
- Specify what version of Widgetkit and Joomla you use

**Comment by acaffeinateddev** [comment]
Turns out the issue is with the CSS, and not with your Widget! I apologize for the trouble and the unnecessary ticket, that was my bad.

However, the link in the wiki I went to WAS behaving a bit oddly, just to let you know. Not sure if this is a bug with the widget or with their site (or me),~~but I've attached a screencap~~. Okay-- sorry for the imgur link, but the image doesn't want to attach and I'm unable to install a better browser on this laptop. http://i.imgur.com/09c41qm.jpg

Thank you for your prompt and thorough response, and thank you for making this Widget in the first place! It does exactly what I need and then some.

**Comment by rvalitov** [comment]
No problem :smile: I'm glad the problem is not with my widget. Regarding the website, the widget is on the left side and it looks fine. The right side has some rendering collisions, because the owners of the website seem to upload an image with invalid dimensions or something.
